### ISSUE TITLE
在 iPad Safari 中列表不能独立滚动，而是整个页面滚动。

### ISSUE THREAD

**Issue by LiangRongjia** [LiangRongjia/treetop-diary#2]
### 问题描述

如题。

### 可能原因

grid 布局被撑开。

### 可能的解决方案

如显式地定义容器高度为 100vh，等等。

**Comment by LiangRongjia** [comment]
### 问题研究

`bottom: 0` 在 Safari 中没有 chromium 中指定高度的效果。故为 `app` `div` 设置高度为 `100%`。

经尝试，高度不宜设置为 `100vh`，对于 Safari ，`100vh` 包括标题栏的部分高度。若不将标题栏上拖隐藏，视图底部将有一部分超出屏幕，被裁去。

经尝试和搜索，在 Safari 中使用非 `static` 定位，尤其是 `fixed` 定位、父元素添加定位，常会出现滚动元素无法滚动的情况。

经搜索，网友建议使用 `-webkit-fill-available` 获取视口高度。但是实践发现该值在 Microsoft Edge 中也被识别，未被忽略，导致在 Edge 中显示异常，不能起到指定高度的作用。

经搜索，采用了媒体查询，为 Safari 定制 CSS 的方法。媒体查询规则采用 https://stackoverflow.com/questions/30102792/css-media-query-to-target-only-ios-devices 中给出的方法：

```css
@supports (-webkit-touch-callout: none) {
    .app {
        height: -webkit-fill-available;
    }
}
```
